### ISSUE TITLE
@Drone in BaseClass  and Tags 

### ISSUE THREAD

**Issue by punitbisht** [cukespace/cukespace#99] opened 2017-05-29 17:47 UTC
I am facing one issue with @Drone annotations in Base Classes.

We have a BaseClass which contains all the customized methods like Click, wait, type .... all the arquillian/selenium library methods a used here .

Other classes/Pages extends this class, no the problem is if we execute the test specifying a tag : 

> mvn looks for each feature file for the tag and launch the browser 
> If tag is not matched, browser is closed .

So if you have 200 feature files and you want to run just one , you will en d up launching 200 browser instances

**Comment by rmannibucau** [comment] 2017-05-29 17:51
Hi

do you inject the driver in the test class (vs a method)?

do you have a (github) sample reproducing the issue?

**Comment by punitbisht** [comment] 2017-05-29 17:55
Hi @rmannibucau 
we are using @Drone annotations in Base class for driver .
we do not inject the driver in test class , we just call the methods in pageobject which in turns call the implementations in baseclass

**Comment by rmannibucau** [comment] 2017-05-29 21:20
Can you try injecting it in the final test class, recall drone got an issue at some point where it was needed but you should get one instance per run normally (~jvm), not one per test.

**Comment by punitbisht** [comment] 2017-05-29 21:23
I can try that for sure, is there any example or reference for injecting the drone ?
or is it possible for you to share some sample code , I don't know how we can inject driver .

**Comment by rmannibucau** [comment] 2017-05-29 21:23
https://github.com/cukespace/cukespace/blob/ca9dc5d312d6b152bbb48e319807b2be1bea3686/examples/src/test/java/cucumber/runtime/arquillian/feature/CukesInBellyFunctionalTest.java

**Comment by punitbisht** [comment] 2017-05-29 21:27
do you mean just the declaration of @Drone in test class?

**Comment by rmannibucau** [comment] 2017-05-29 21:30
yep, depending the drone version it can help (maybe also check the one you use), 2.0.0.Final is known to work (at least with tomee adapters)

**Comment by punitbisht** [comment] 2017-05-29 21:31
I am using 2.0.0-Final, so if I have 200 test classes, I have to mention in all ?

**Comment by rmannibucau** [comment] 2017-05-29 21:33
For now I'd like to validate it comes from it so maybe extract 5-6 to check it is coming from that. There are a lot of potential cause until we have a sample reproducing it I can check out locally. (like surefire fork count etc)

**Comment by punitbisht** [comment] 2017-05-29 21:36
I tried, didn't solve the problem .


 I am getting this message 

WARNING: Injection point DronePointImpl{droneClass=interface org.openqa.selenium.WebDriver, annotations=[@org.jboss.arquillian.drone.api.annotation.Drone()], lifecycle=CLASS} was not prepared yet. It will be prepared now, but it's recommended that all drones with class lifecycle are prepared in @BeforeClass by the DroneLifecycleManager!

**Comment by punitbisht** [comment] 2017-05-30 05:05
https://github.com/punitbisht/BasePage_Drone

Created a sample project, this might help you to trouble shoot the problem

**Comment by rmannibucau** [comment] 2017-05-30 08:08
@punitbisht take care this sample doesnt build: com.pearson.aimswebplus:aimswebplus-rosterclient:jar:0.0.1-SNAPSHOT

**Comment by rmannibucau** [comment] 2017-05-30 08:31
Hmm, tested and seems injecting the driver in the test class works:

    @Drone
    private WebDriver driver;

It makes the driver instantiated before the enrichment and avoids the warnings.

Then you are class managed so you have one browser per test class of the life duration of the class. For phantomjs i used that hack to keep the same instance:


    public class SingleForkPhantomJSDriverFactory extends PhantomJSDriverFactory
        // sucks and useless but Drone get generics brutally so we need it
        implements Configurator<PhantomJSDriver, WebDriverConfiguration>, Instantiator<PhantomJSDriver, WebDriverConfiguration>, Destructor<PhantomJSDriver> {
    private static final Logger LOGGER = Logger.getLogger(SingleForkPhantomJSDriverFactory.class.getName());
    private static final int DEFAULT_MAX_TEST = -1;

    private static volatile int maxTest = DEFAULT_MAX_TEST;
    private static volatile PhantomJSDriver driver = null;
    private static volatile int count = 0;
    private static volatile boolean hookSet;

    public SingleForkPhantomJSDriverFactory() {
        if (!hookSet) {
            synchronized (SingleForkPhantomJSDriverFactory.class) {
                if (!hookSet) {
                    Runtime.getRuntime().addShutdownHook(new Thread() {
                        @Override
                        public void run() {
                            if (driver != null) {
                                SingleForkPhantomJSDriverFactory.super.destroyInstance(driver);
                                LOGGER.info("Destroyed PhantomJSDriver");
                            }
                        }
                    });
                    hookSet = true;
                }
            }
        }
    }

    @Override
    public void destroyInstance(final PhantomJSDriver instance) {
        synchronized (SingleForkPhantomJSDriverFactory.class) {
            count++;
            if (maxTest > 0 && maxTest <= count) {
                count = 0;
                driver = null;
                super.destroyInstance(instance);
                LOGGER.info("Resetting PhantomJSDriver (maxTest=" + maxTest + ") reached");
            }
        }
    }

    @Override
    public PhantomJSDriver createInstance(final WebDriverConfiguration configuration) {
        if (driver == null) {
            synchronized (SingleForkPhantomJSDriverFactory.class) {
                if (driver == null) {
                    final Capabilities configurationCapabilities = configuration.getCapabilities();
                    final Object capability = configurationCapabilities.getCapability("arquillian.phantomjs.maxTests");
                    if (capability != null) {
                        maxTest = Integer.parseInt(String.valueOf(capability.toString()));
                    }
                    final DesiredCapabilities capabilities = new DesiredCapabilities(configurationCapabilities);
                    String executablePath = String.class.cast(capabilities.getCapability(PhantomJSDriverService.PHANTOMJS_EXECUTABLE_PATH_PROPERTY));
                    if (executablePath == null || executablePath.isEmpty()) {
                        capabilities.setCapability(PhantomJSDriverService.PHANTOMJS_EXECUTABLE_PATH_PROPERTY, new File("target/drone-phantomjs").getAbsolutePath());
                    }

                    final Object cliArgs = capabilities.getCapability("phantomjs.cli.args");
                    if (cliArgs != null && String.class.isInstance(cliArgs)) {
                        capabilities.setCapability("phantomjs.cli.args", cliArgs.toString().split(" "));
                    }

                    try {
                        driver = PhantomJSDriver.class.cast(SingleForkPhantomJSDriverFactory.class.getClassLoader()
                                .loadClass(configuration.getImplementationClass())
                                .getConstructor(PhantomJSDriverService.class, Capabilities.class)
                                .newInstance(ResolvingPhantomJSDriverService.createDefaultService(capabilities), capabilities));
                    } catch (final Exception e) {
                        throw new IllegalStateException(e);
                    }

                    LOGGER.info("Created PhantomJSDriver");
                }
            }
        }
        return driver;
    }
    }


    public class PhantomJSExtension implements LoadableExtension {
    @Override
    public void register(final ExtensionBuilder builder) {
        // override default ones which is pretty slow when created by method but we do it in this extension
        // to stay compliant with default drone behavior if used
        builder.override(Configurator.class, PhantomJSDriverFactory.class, SingleForkPhantomJSDriverFactory.class);
        builder.override(Instantiator.class, PhantomJSDriverFactory.class, SingleForkPhantomJSDriverFactory.class);
        builder.override(Destructor.class, PhantomJSDriverFactory.class, SingleForkPhantomJSDriverFactory.class);
    }
    }


you can surely use the same for firefox or chrome

**Comment by punitbisht** [comment] 2017-05-30 11:40
@rmannibucau you mean declaring 
@Drone
 private WebDriver driver;


in page objects or step defs ?

**Comment by rmannibucau** [comment] 2017-05-30 12:05
in the test (not page objects or steps), where you put @RunWith

**Comment by punitbisht** [comment] 2017-05-30 12:27
I tried, same thing .

Didn't helped me

**Comment by rmannibucau** [comment] 2017-05-30 12:51
@punitbisht we agree it removes the warning you mentionned right? if not then something else is fishy cause it worked well for me in your sample

**Comment by punitbisht** [comment] 2017-05-30 12:54
@rmannibucau yes it removes the warning, but still launches browser when you run test specifying the test
<mvn -Pstaging clean "-Dcucumber.options=-t @tag" test>

**Comment by rmannibucau** [comment] 2017-05-30 12:54
@punitbisht this is expected since the browser is bound to the test which has the driver then.

**Comment by punitbisht** [comment] 2017-05-30 12:56
@rmannibucau , Okay . is there any way we can disable the launch of browser if tag is not matched for the feature

**Comment by rmannibucau** [comment] 2017-05-30 12:57
@punitbisht means you disable drone for that run, can be done through a maven profile ensuring you run without the drone/graphene implementation I think.

**Comment by punitbisht** [comment] 2017-05-30 12:59
example pleas e

**Comment by rmannibucau** [comment] 2017-05-30 13:04
sadly don't have one ready to provide, you can probably ask graphene project about it, maybe they have a flag to do it I'm not aware of (would be neat here but not in other cases so not sure)

**Comment by punitbisht** [comment] 2017-05-31 13:03
HI @rmannibucau - https://github.com/arquillian/arquillian-extension-drone/issues/93#issuecomment-305178181

See the response from arquillian team. your insights are very important there and may be we can solve this problem, which will help everyone using cukespace .

one more request , can you delete your comment 

> @punitbisht take care this sample doesnt build: com.pearson.aimswebplus:aimswebplus-rosterclient:jar:0.0.1-SNAPSHOT

>

**Comment by rmannibucau** [comment] 2017-05-31 13:11
commented on drone issue

**Comment by punitbisht** [comment] 2017-06-21 00:48
@rmannibucau I tried https://github.com/arquillian/arquillian-extension-drone/pull/94 solution , didn't work for me . wanted to check with you if you gave a try to this

**Comment by rmannibucau** [comment] 2017-06-21 05:52
I didn't since responsability fully moved to drone

**Comment by punitbisht** [comment] 2017-06-21 13:28
@rmannibucau would you mind trying it once, I tried everything and looks like there are problems . if you are also not able to use this flag, I will report that issue again

**Comment by rmannibucau** [comment] 2017-06-21 14:44
yep it works, upgrade drone to 2.2.0 (take care they didnt use .Final), cukespace to 1.6.7 and set -Darquillian.drone.skip.creation=true

**Comment by punitbisht** [comment] 2017-07-07 16:41
@rmannibucau I tried this and this works when we set set
```
 -Darquillian.drone.skip.creation=true
``` 
in command line. 
Now the real use of this flag is when we set the value on Before method, but when I tried this 
```
 @Before
    public void setUpTest(Scenario scenario) throws Exception {
        Properties props = System.getProperties();
        props.setProperty("arquillian.drone.skip.creation", "true");
        System.out.println(props);
    }
```
the browser instance launched before the first statement in method

**Comment by rmannibucau** [comment] 2017-07-07 16:53
@punitbisht sure cause @Before is after arquillian lifecycle, same would apply for @BeforeClass. You can do it in a static block of the test class but it is not that great. Using arquillian.xml can be another way if you use filtering.

**Comment by punitbisht** [comment] 2017-07-07 16:57
Nice Points @rmannibucau , ill see if I can get something on arquillian.xml filtering. would you mind sharing some resources to look for examples

**Comment by rmannibucau** [comment] 2017-07-07 17:03
outch, throught drone followed the arquillian pattern to configure extensions from arquillian.xml but seems they just added the system property support directly (https://github.com/MatousJobanek/arquillian-extension-drone/blob/7caeff138fc2578539971c5fe4b6e5f00ec36056/drone-impl/src/main/java/org/jboss/arquillian/drone/impl/DroneTestEnricher.java#L175)

you can write a small arquillian LoadableExtension (just a SPI to register) just doing the System.setProperty, will be done early enough to should work for "client" tests. Does it sound easier?

**Comment by punitbisht** [comment] 2017-07-07 17:17
I think static method looks easy to me :) , but wondering what is the best way to access tags associated with the feature file within static method and comparing them with those passed on commandline with 
```
"-Dcucumber.options=-t @tag1, @tag2,@tag3"
```

**Comment by rmannibucau** [comment] 2017-07-07 17:30
if you pass a system property then System.getProperty() sounds like a good fit

**Comment by punitbisht** [comment] 2017-07-07 19:37
@rmannibucau how can we access the tags in feature file within the static method . 
We can access the tags passed as system property during execution, but comparing system property with tags in feature file is necessary

**Comment by rmannibucau** [comment] 2017-07-07 19:58
How would you do with cucumber? Think it will lead to doing some contains or pattern matching on the system property which is way easier than changing arquillian drone lifecycle to make it lzy and matching your use case.

**Comment by punitbisht** [comment] 2017-07-07 20:08
```
@Before
    public void setUpTest(Scenario scenario) throws Exception {
        Properties props = System.getProperties();
        props.setProperty("arquillian.drone.skip.creation", "true");
        System.out.println(props);
    }
```
This method above have access to scenario object, this scenario object can be used to get tag names from feature file which later I can match with the passed tag in command line 
.

But in static block I can access the command line parameters but not the scenario object to get tags declared in feature file. Hence I can't do the pattern matching

**Comment by rmannibucau** [comment] 2017-07-07 20:18
Yes but issue is drone is eager and not lazy so cucumber arrives too late. Probably back to the original drone issue.

Side note: doing some maven profile you can workaround it easily

**Comment by punitbisht** [comment] 2017-07-07 20:25
Side note: doing some maven profile you can workaround it easily - any example ?

**Comment by punitbisht** [comment] 2017-07-10 13:58
@rmannibucau I have fixed the issue by Passing the ```-Darquillian.drone.skip.creation="true"``` at  the command line and then matching the tags inside @Before method and setting the ```arquillian.drone.skip.creation = "false"```

**Comment by punitbisht** [comment] 2017-07-13 16:40
@rmannibucau  Please refer https://github.com/arquillian/arquillian-extension-drone/issues/102#issuecomment-315044536

**Comment by punitbisht** [comment] 2017-08-02 16:32
@rmannibucau  we have fixed this issue, not a very nice way though. we have two files for a step des:
1) cucumber files - contains cucumber options including glue
2) Actual step defs - which is in a different package and glued with the respective cucumber files

**Comment by punitbisht** [comment] 2017-08-02 16:33
This way drone is not initializing at the time of feature file scan for tags

**Comment by punitbisht** [comment] 2017-12-05 23:56
@rmannibucau  if you want you can close this issue as we have fixed this issue.

**Closed** 2017-12-06 05:55 UTC
